plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'jacoco'
}

group = 'ks.com'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // spring
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

    // kafka
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework:spring-messaging'

    // lombok
    implementation 'org.springframework.boot:spring-boot-starter-web'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'

    // DB
    runtimeOnly 'org.postgresql:postgresql'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'

    // view
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // websocket
    implementation'org.springframework.boot:spring-boot-starter-websocket'

    // test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation "org.junit.jupiter:junit-jupiter:5.5.2"
    testImplementation "org.mockito:mockito-core:3.12.4"
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'

    // jwt
    implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'

    // Swagger UI
    implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.8.11'
}

jacoco {
    toolVersion = "0.8.11"
    reportsDirectory = layout.buildDirectory.dir('jacocoReport')
}

test {
    finalizedBy jacocoTestReport
    useJUnitPlatform()
}

jacocoTestReport {
    dependsOn test, compileJava, processResources
    reports {
        xml.required = false
        html.required = true
        csv.required = false
    }

    executionData.setFrom(fileTree(project.buildDir).include('jacoco/*.exec'))

    classDirectories.setFrom(
            files(project.sourceSets.main.output.classesDirs.files.collect {
                fileTree(dir: it, exclude: [
                        '**/BudgetManagementProjectApplication.class',
                        '**/global/**',
                        '**/*Dto*',
                        '**/*Entity*',
                        '**/*Repository',
                        '**/feature/role/**',
                        '**/feature/token/**',
                        '**/feature/expenditure/service/ExpenditureSchedulerService', // 스케줄러 자체는 제외
                ])
            })
    )
    finalizedBy 'jacocoTestCoverageVerification'
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport

    violationRules {
        rule {
            element = 'BUNDLE'
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.8
            }
        }
    }

    classDirectories.setFrom(
            files(project.sourceSets.main.output.classesDirs.files.collect {
                fileTree(dir: it, exclude: [
                        '**/BudgetManagementProjectApplication.class',
                        '**/global/**',
                        '**/*Dto*',
                        '**/*Entity*',
                        '**/*Repository',
                        '**/feature/role/**',
                        '**/feature/token/**',
                        '**/feature/expenditure/service/ExpenditureService',
                        '**/feature/expenditure/service/ExpenditureSchedulerService',
                        '**/feature/expenditure/service/ExpenditureSchedulerService$SchedulerResult', // 내부 클래스 명시 제외
                        '**/feature/budget/service/BudgetCategoryService',
                ])
            })
    )
}

check {
    dependsOn jacocoTestCoverageVerification
}