plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.4'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'org.springdoc.openapi-gradle-plugin' version '1.8.0'
    id 'jacoco'
}

group = 'ks.com'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    // Spring Core & Security
    implementation 'org.springframework.boot:spring-boot-starter-batch'
    implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'

    // Database
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    // View Template
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

    // Message Queue & Real-time Communication
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework:spring-messaging'
    implementation 'org.springframework.boot:spring-boot-starter-websocket'

    // Cache - redis
    implementation 'org.springframework.boot:spring-boot-starter-data-redis'

    // Mail
    implementation 'org.springframework.boot:spring-boot-starter-mail'

    // JWT Authentication
    implementation group: 'io.jsonwebtoken', name: 'jjwt-api', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-impl', version: '0.11.5'
    runtimeOnly group: 'io.jsonwebtoken', name: 'jjwt-jackson', version: '0.11.5'

    // Validation
    implementation 'jakarta.validation:jakarta.validation-api:3.0.2'

    // API Documentation - Swagger
    implementation group: 'org.springdoc', name: 'springdoc-openapi-starter-webmvc-ui', version: '2.8.11'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'

    // Lombok
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // Test
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.springframework.batch:spring-batch-test'
    testImplementation 'org.springframework.security:spring-security-test'
    testImplementation "org.junit.jupiter:junit-jupiter:5.5.2"
    testImplementation "org.mockito:mockito-core:3.12.4"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

jacoco {
    toolVersion = "0.8.11"
    reportsDirectory = layout.buildDirectory.dir('jacocoReport')
}

test {
    finalizedBy jacocoTestReport
    useJUnitPlatform()
}

jacocoTestReport {
    dependsOn test, compileJava, processResources
    reports {
        xml.required = false
        html.required = true
        csv.required = false
    }

    executionData.setFrom(fileTree(project.buildDir).include('jacoco/*.exec'))

    classDirectories.setFrom(
            files(project.sourceSets.main.output.classesDirs.files.collect {
                fileTree(dir: it, exclude: [
                        // Application 클래스
                        '**/BudgetManagementProjectApplication.class',

                        // Config 패키지 전체
                        '**/config/**',
                        '**/configuration/**',

                        // Global 패키지
                        '**/global/**',

                        // DTO, Entity, Repository
                        '**/*Dto.class',
                        '**/*Dto$*.class',
                        '**/*Request.class',
                        '**/*Request$*.class',
                        '**/*Response.class',
                        '**/*Response$*.class',
                        '**/*Entity.class',
                        '**/*Entity$*.class',
                        '**/*Repository.class',
                        '**/*Repository$*.class',

                        // Role, Token 패키지
                        '**/feature/role/**',
                        '**/feature/token/**',

                        // 특정 서비스
                        '**/feature/expenditure/service/ExpenditureSchedulerService.class',
                        '**/feature/budget/service/BudgetCategoryService.class',

                        // Filter, Security 관련
                        '**/*Filter.class',
                        '**/*Filter$*.class',

                        // Exception Handler
                        '**/*ExceptionHandler.class',
                        '**/*ExceptionHandler$*.class',

                        // Enum 클래스
                        '**/*Enum.class',
                        '**/*Status.class',
                ])
            })
    )
    finalizedBy 'jacocoTestCoverageVerification'
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport

    violationRules {
        rule {
            element = 'BUNDLE'
            limit {
                counter = 'LINE'
                value = 'COVEREDRATIO'
                minimum = 0.7
            }
        }
    }

    classDirectories.setFrom(
            files(project.sourceSets.main.output.classesDirs.files.collect {
                fileTree(dir: it, exclude: [
                        // Application 클래스
                        '**/BudgetManagementProjectApplication.class',

                        // Config 패키지 전체
                        '**/config/**',
                        '**/configuration/**',

                        // Global 패키지
                        '**/global/**',

                        // DTO, Entity, Repository
                        '**/dto',
                        '**/dto/**',
                        '**/*Request.class',
                        '**/*Request$*.class',
                        '**/*Response.class',
                        '**/*Response$*.class',
                        '**/entity',
                        '**/entity/**',
                        '**/*Repository.class',
                        '**/*Repository$*.class',

                        // Role, Token 패키지
                        '**/feature/role/**',
                        '**/feature/token/**',

                        // 특정 서비스
                        '**/feature/expenditure/service/ExpenditureSchedulerService.class',
                        '**/feature/budget/service/BudgetCategoryService.class',

                        // Filter, Security 관련
                        '**/*Filter.class',
                        '**/*Filter$*.class',

                        // Exception Handler
                        '**/*ExceptionHandler.class',
                        '**/*ExceptionHandler$*.class',

                        // Enum 클래스
                        '**/*Enum.class',
                        '**/*Status.class',
                ])
            })
    )
}

check {
    dependsOn jacocoTestCoverageVerification
}

openApi {
    apiDocsUrl.set("http://localhost:8080/v3/api-docs")
    outputDir.set(file("$buildDir/openapi"))
    outputFileName.set("openapi.json")
}