services:

  postgresql-db:
    image: postgres:13.9
    container_name: postgresql-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - study_net

  redis-db:
    container_name: redis-db
    image: redis:7-alpine
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    env_file:
      - .env
    networks:
      - study_net

networks:
  study_net:

volumes:
  postgres_data:
  redis_data: