spring:

  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${POSTGRESQL_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      username: ${REDIS_USER}

jwt:
  secret: ${JWT_SECRET}