name: Deploy Swagger to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Start Application
        run: |
          ./gradlew bootRun > /dev/null 2>&1 &

      - name: Wait for application
        run: |
          timeout 120 bash -c 'until curl -f http://localhost:9091/actuator/health; do sleep 2; done'

      - name: Generate OpenAPI JSON
        run: |
          curl http://localhost:9091/v3/api-docs -o swagger-ui/openapi.json

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./swagger-ui

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4